### ISSUE TITLE
Disperse Honorariums

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#102]
Building on #96  and #101, post-event we'll need to coordinate dispersing the honorariums

**Comment by dcwalk** [comment]
In the midst! After Monday we should have this mostly in hand

**Comment by dcwalk** [comment]
Update: basically done-- waiting on a couple lingering emails and we can close this out!

**Comment by benhylau** [comment]
Thanks for sorting this all out @dcwalk was a lot of coordinating!

**Comment by dcwalk** [comment]
I'm going leave this until August 30 then call it closed and finalize #101, we can revisit the final honorarium as needed.

**Comment by dcwalk** [comment]
These was donnnnne!
