### ISSUE TITLE
Live stream server and failover plan

### ISSUE THREAD

**Issue by benhylau** [ournetworks/2018#108]
The HTTP stream is DNS round-robin across 3 servers managed by @ASoTNetworks.

The IPFS stream will use a server donated by Justin as primary. We will ready a PR to fallback to ipfs.io if that server falls over due to unexpected amount of traffic. Something like:

```
diff --git a/js/live-stream-embed.js b/js/live-stream-embed.js
index 94e3e28..214a9c7 100644
--- a/js/live-stream-embed.js
+++ b/js/live-stream-embed.js
@@ -1,6 +1,6 @@
 // Live Stream Video

-var ipfs_gateway_self = 'http://ipfs01.vz.jgndata.biz:8080'; // IPFS gateway of this node
+var ipfs_gateway_self = 'https://ipfs.io'; // IPFS gateway of this node
 var ipfs_gateway_origin = 'http://ipfs-server.mesh.world:8080'; // IPFS gateway of origin stream
 var m3u8_ipfs = 'http://ipfs-mirror-0.mesh.world/live.m3u8'; // File path to m3u8 with IPFS content via HTTP server
 // var m3u8_ipfs='__IPFS_GATEWAY_ORIGIN__/ipns/__IPFS_ID_ORIGIN__'; // URL to m3u8 via IPNS (uncomment to enable)
```

cc. @darkdrgn2k

**Comment by benhylau** [comment]
Confirmed that ipfs.io streams fine, responses have `access-control-allow-origin: *`.

**Comment by dcwalk** [comment]
I an gonna close this @benhylau. I feel like you are keeping any important upstream, reopen if I've misjudged!
