### ISSUE TITLE
Livestream retrospective

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#120]
I know @benhylau, @ASOTnetworks, @darkdrgn2k and @Shrinks99 were planning on a live stream post mortem, would be good to figure out that date and attend...?

**Comment by benhylau** [comment]
During HOPE could make sense, as a call. Otherwise week after HOPE before dweb works too.

**Comment by Shrinks99** [comment]
I've got good notes on most of the things we want to talk about.  Current plan (me talking with @darkdrgn2k ) is to have the call after HOPE.

**Comment by dcwalk** [comment]
Cool! Can you post the date once you decide here? (Or distribute any poll you are using to finalize?) Thanks :)

**Comment by dcwalk** [comment]
Hi @Shrinks99 @benhylau @darkdrgn2k, could you update us all on when this is scheduled?

Thanks!

**Comment by benhylau** [comment]
Please put your availability for Wed / Thurs:
https://www.when2meet.com/?6993128-1mtbz

**Comment by dcwalk** [comment]
This happened here: https://hackmd.io/SEB5MgPoQWGYTWA4Mk5JRA#, updated readme in https://github.com/ournetworks/2018/commit/ba34bc9ba142bf8bb71e46199c9fe5f2ef7c1466
