### ISSUE TITLE
Archive the 2017 and 2018 versions of the site

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#125]
Update 2018-08-11 with tasks:

- [x] tag 2017 release --> https://github.com/ournetworks/ournetworks.ca/releases/tag/2017
  - [x] add patch to `2017` build to indicate event has passed (in https://github.com/ournetworks/ournetworks.ca/pull/82)
- [x] tag 2018 release --> https://github.com/ournetworks/ournetworks.ca/releases/tag/2018 
- [x] 2017 and 2018 redirects are set up
- [x] deploy 2017 and 2018 archived versions, update nginx config
  - [x] add wildcard DNS record
  - [x] add `2017` and `2018` server blocks
  - [x] add letsencrypt support for new domains
- [x] final site update for "looking ahead to 2019 phase" --> https://github.com/ournetworks/ournetworks.ca/pull/87

---

We want to preserve the  look of 2017, 2018 versions of the site had a brief discussion with @garrying about subdomain vs/ subdirectory for how to handle this. Need to discuss further, including how to deploy and maintain code.

**Comment by benhylau** [comment]
Can we `2017.ournetworks.ca` and `2018.ournetworks.ca`?

**Comment by garrying** [comment]
I'm partial to the subdomain (`2018.ournetworks.ca`) approach, with a couple thoughts:
- Create a tag/release in https://github.com/ournetworks/ournetworks.ca for `2018` when we feel that it's in an archivable state
- Redirect from `ournetworks.ca/2018` to `2018.ournetworks.ca` that will persist through each release
- We do a final build from the `2018` release, and either:
  - Commit final build to a `2018.ournetworks.ca` repo on GitHub (let GH pages host) or
  - Upload final build to our Digital Ocean VPS, and setup sub-domain in nginx

**Comment by dcwalk** [comment]
Those thoughts work for me! Only thing I'd weigh in on is that I'd prefer the final build is on our VPS rather than GH pages hosting.

**Comment by dcwalk** [comment]
- I think this: https://github.com/ournetworks/ournetworks.ca/tree/8bed6677c49b813896ce05ddcec4cd9e275a9c3e is a good candidate for the 2017 snapshot!! (tho do we want a banner saying it is over like we'll have for 2018?

**Comment by garrying** [comment]
Updated the task list in this issue. A few notes:
- https://2017.ournetworks.ca and https://2018.ournetworks.ca are available with their respective folders under `/var/www/` 
- Deploying the builds is a manual process at the moment
  - Are we ok with this? or do we want to spend time on automating through Travis?
- I haven't been able to find a good way to support wildcard domains with our registrar. Each domain has their own certificate for now. [Certbot's DNS plugin support so far](https://certbot.eff.org/docs/using.html#dns-plugins).

**Comment by dcwalk** [comment]
@garrying it looks like a version has been deployed for 2018/2017, but we haven't tagged a release (and I think there might be a commit or two to clean up both).

Are you imagining we reploy after those?
Manual deployment seems fine given the pace at which I imagine we will (v. infrequently)

**Comment by garrying** [comment]
@dcwalk Yeah, we'd redeploy from the tagged releases after clean up. At the moment: `2017` from https://github.com/ournetworks/ournetworks.ca/commit/8bed6677c49b813896ce05ddcec4cd9e275a9c3e and `2018` from https://github.com/ournetworks/ournetworks.ca/commit/450b092f7ec61caf61ed773922631c65c37e2c00

**Comment by garrying** [comment]
Thinking this could be closed. URLs are:
- https://2017.ournetworks.ca
- https://2018.ournetworks.ca

with redirects at the top-level domain: `ournetworks.ca/2017`, `ournetworks.ca/2018`
