### ISSUE TITLE
Post mortem on Yami-ichi shareback with TMAC

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#128]
@ana0 will lead on this mid-September

TODO: 
- ~add postmortem notes to 2018 repo as md~ (I think this is covered?)
- [x] final email followup

**Comment by dcwalk** [comment]
half-happened, . Final follow up around budget numbers:

- what the drink tickets would cost
- cleaning costs
- security? 
- tables?

**Comment by ana0** [comment]
SENT

**Comment by dcwalk** [comment]
Okay! We decided we were just gonna leave this one be. I'm gonna close this as the email was sent awhile ago :)
