### ISSUE TITLE
Video and mailing list announcement to attendees 

### ISSUE THREAD

**Issue by benhylau** [ournetworks/2018#129]
- [x] Draft email:
  - Announce IPFS archive
  - Announce YouTube publishing plan
  - Announce mailing list for future Our Networks
  - Open hour feedback+form (also #124)
- Update website pointing to video archive (tracked in #87 )
- [x] Request pinning from ipfs.io (update from @benhylau 10/01: this is in progress)
- [x] Send email to presenters+attendees with link to mailing list
- [x] Send email to mailinglist (see #95)

**Comment by dcwalk** [comment]
I think some of the todos on here are handled elsewhere, marking so in the above comment

**Comment by dcwalk** [comment]
This was DONE! Closing 💃
