### ISSUE TITLE
Revisit account access and management policies

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#131]
We should develop/revisit our Our Networks accounts and the access/management policies we have around that (e.g., we are on a few services platforms and generally share passwords.

Should ensure that it reflects our needs/capacity going forward to 2019. Also whether they need to be updated for people

Services:
- single acct:
  - BPT
  - Paypal
  - Twitter
  - Mailing list (?) - Mayfirst
- group/individual accts:
  - Bank
  - Namecheap
  - Digital Ocean
  - Twitter
  - Youtube
  - GH Org
  
Unused:
- Stripe
- Dtube (Hank?)

**Comment by dcwalk** [comment]
Yeah, I was thinking a list+ensure we've spread access appropriately!

**Comment by Shrinks99** [comment]
I will let you know what happens with DTube once they send me account login information.  Alternatively I can claim the name for a whole one dollar in the mean time and get it instantly so I can give you credentials.

Nothing is tied to my email once the account is created, they are just using it to give me a private key.  Crypto and all that jazz.

**Comment by dcwalk** [comment]
This issue was moved to ournetworks/2019#2
