### ISSUE TITLE
set standing biweekly 30min planning call

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#17]
Hey all! To keep us on track with organizing I was hoping we could set *a standing, bi-weekly planning call* that will run until from Feb to May (at that point we may want to switch up schedules as we get closer to). I expect them to be 30 mins as we should aim to mostly just check in and use it as an anchor/touchstone for work.

Here is *Poll* to set a time, all times ET: https://www.when2meet.com/?6640197-1uoRe (NEW POLL!)

Looking forward to chatting with you all :)

**Comment by jkms** [comment]
Filled it out. Unfortunately, being 3 hours behind you guys makes my availability tricky :P

**Comment by dcwalk** [comment]
ack @jkms -- I just realized I set this only until 8pm ET. That isn't a hard limit that was intentional, just morning brain... I'm assuming you'd potentially have some avail 8-10pm ET M-F?

Unfortunately we can't edit the when2meet, but here is a new one (sorry!): https://www.when2meet.com/?6640197-1uoRe, do you mind filling in again?

**Comment by jkms** [comment]
Done :)

**Comment by benhylau** [comment]
Filled, also booked https://appear.in/ournetworks for our meetings

**Comment by patcon** [comment]
Done and done!

**Comment by garrying** [comment]
Filled

**Comment by darkdrgn2k** [comment]
Looks like you guys have a good solid team together for this conf, glad to see.

If there is anything you need help with i'm def available to help, however i may not be around for the week-day part of the conf (i may be traveling to new york earlier).

**Comment by dcwalk** [comment]
Awesome thanks all! Let's go with Saturdays for now, I've updated the README with details here: https://github.com/ournetworks/2018#planning and have a google calendar set up for people who want to add to their calendaring app: https://calendar.google.com/calendar/ical/aers7atolh0uurlfmkoki9kikg%40group.calendar.google.com/public/basic.ics

May and June get a little hinky, but I have some big chunks of time where I'll be unavail for planning so I'm hoping we're making good time in May!
