### ISSUE TITLE
Establish 2018 look

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#20]
This (ideally?) would be something we could work with a designer to create! It would impact website, advertising, swag, and day-of...

**2018-03-10** call we discussed the following:
- website refresh
- logo (but better specify range of uses in line with Swag #36 and Conference use, e.g., projected? posters?) 
   - presentation buffer
   - posters / handbills

**Comment by garrying** [comment]
Initial look-and-feel concept ideas from Marlo:
![soon-web-v1-homepage](https://user-images.githubusercontent.com/227587/38456805-a0d251b6-3a56-11e8-90b5-ccf7ac58905d.png)
![soon-web-v1-landingpage](https://user-images.githubusercontent.com/227587/38456812-a36d4692-3a56-11e8-9aae-585ce71293f2.png)

**Comment by garrying** [comment]
April 7: Regrouping with Marlo today for design feedback and sync on deliverables.

**Comment by dcwalk** [comment]
Hey @garrying -- I'm digging the colour and the textures on the initial concepts!

My thoughts:
- I feel like our networks should be scrappy rather than super 'clean' (DIY/DIWO!!!)
- I don't know how to invoke it, but something about participation/collaboration feels cool here
- how do you see a discrete logo complementing this look?

**Comment by garrying** [comment]
Marlo and I decided on creating a Google Doc: https://docs.google.com/document/d/1sP3qt87nJBq1UmoCfddiy9PuyuOLer1KnVF54FeE5Cw/edit?usp=sharing

We're going to post deliverables and major decisions in this, and corresponding, issues as they come up.

**Comment by dcwalk** [comment]
okie @garrying! Can you move out the relevant notes (e.g. timeline, deliverables?) to the gh issues where we are tracking here? I'm thinking about people who will not be as involved in the process.

Also, can you add the gdoc to the Our Networks Google Drive folder?

**Comment by garrying** [comment]
- Moved the doc to the shared folder and fix the permissions. Please leave comments as I think there are parts of it that are WIP, especially the deliverables timeline
- I think an earlier timeline for IA and content launch is fine—we should be fine to accommodate if the content/details are ready by the beginning of May
- I'll ask about cc-by-sa and get back to the group on credits for the design work with Marlo
- The Dropbox is for Marlo and I to be synced with in-progress design assets (repurposing a workflow that we're familiar with for now). We're going to move final assets to the repo as they become ready

**Comment by garrying** [comment]
April 13 Update: We're not going to have updated concepts to review for the April 14th regroup. I'll post up anything comes up in the following week and ping everyone for a look.

**Comment by garrying** [comment]
Thinking this can be closed with https://github.com/ournetworks/artwork/pull/1 merged and progress tracking in #43 #42
