### ISSUE TITLE
Develop sponsorship package and shortlist sponsership possibilities

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#23]
Running list of Larger orgs within the domain:
- [CIRA](https://cira.ca/), I'm a member! technically/aspirationally(?) ournetworks.ca is a member too because we registered a tld -- just info@cira.ca and ask about where to email? Maybe their Community Investment [program lead](https://cira.ca/blog/192)? 
- [ISOC Canada](http://internetsociety.ca/), [ISOC](https://www.internetsociety.org/beyond-the-net) -- I think we go thru ISOC Canada first, and I'd suggest emailing people we worked with last year. I think I'm a member (?)
- [Mozilla](https://www.mozilla.org/en-US/foundation/), they release a Healthy Internet report, this is a healthy (intra/)internet conference ~Through their ["Dev Engagement form"](https://bugzilla.mozilla.org/form.dev-engagement-event)~ <<- on second thought I don't think we should use that request

---
Types of sponsorship and what we are able to offer [**moved to Sponsorship Package**](https://docs.google.com/document/d/13GMuyFwwauvsq92XwkuVWL4BsY24IDIPbcFLEHyfyw8/edit)

---
Sponsorship possibilities moved to our **Pipline**

**Comment by dcwalk** [comment]
Checked in on 2018-03-10 about this --
- no new "larger domain specific orgs spoke"
- identify what possible things we could provide (brainstorm in this issue)

But we needed more conversation and so will focus in on in April call

**Comment by dcwalk** [comment]
Also, @patcon surfaced some important considerations about how to frame asks, this brainstorming is happening in #23, in the meantime, want to make sure we are keeping this [recent discussion in mind](https://twitter.com/sehurlburt/status/966447774584598534) (in the top of #13, which should track our actual successes!)

**Comment by ana0** [comment]
Example of (ambitious) sponsorship tiers from an upcoming hackathon http://cryptochickshackathon.com/wp-content/uploads/2018/02/CryptoChicks-SponsorshipPackage-2018_02_21.pdf

**Comment by dcwalk** [comment]
Hey @ana0 and @benhylau I roughed out the sponsorship doc: [**Sponsorship Package DRAFT**](https://docs.google.com/document/d/13GMuyFwwauvsq92XwkuVWL4BsY24IDIPbcFLEHyfyw8/edit)

**Comment by ana0** [comment]
I left some comments in the draft and started a brainstorming list of possible sponsors (pending their ideological approval)

**Comment by dcwalk** [comment]
Awesome! Okay so I did some digging and edited major sponser contact details above

**Comment by ana0** [comment]
I added a (very rough) section to the sponsorship draft after talking with some friends about what their companies would want to see when considering sponsoring us.  Kind of an "about the event"/"about our audience" section.

**Comment by dcwalk** [comment]
Great @ana0, yeah I assumed we'd want to add something about the event etc..., but was deferring in my laziness! 

Hey @patcon did you have a chance to consider whether you are interested in leading sponsorship?

**Comment by dcwalk** [comment]
@ana0 @patcon @garrying @benhylau -- can we aim to note here that we agree with the initial sponsorship packages as drafted:
https://docs.google.com/document/d/13GMuyFwwauvsq92XwkuVWL4BsY24IDIPbcFLEHyfyw8/edit#

**Comment by garrying** [comment]
Had a look at the packages they seem good to me.

**Comment by ana0** [comment]
Can confirm, have checked it out, and it's awesome now!

**Comment by dcwalk** [comment]
Okay, I'm gonna close this as we did the initial thing (package! shortlist!) I'll spawn a new issue for firming up our second pass of sponsorship people?
