### ISSUE TITLE
Shortlist designers

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#24]

**Comment by dcwalk** [comment]
Here were some people/groups I was thinking it would be neat to reach out to: 
- https://thepublicstudio.ca/
- [repetitive press](https://www.facebook.com/pg/Repetitive-Press-1673621286222507/about/?ref=page_internal)
- maybe we could email someone from radical design school? http://radicaldesign.school/

**Comment by garrying** [comment]
Initial thoughts:
- http://value-form.com (Reached out. Friend that I've collaborated with before)
- Ross Zurowski (Based in SF at the moment. Doing a bit of Dat/Beaker experimenting. Might be coming up for the conf)
- Ali S. Qadeer (OCAD U. Might know people who can help out)

**Comment by dcwalk** [comment]
@garrying to follow this own, aiming for within the next week to have some updates

**Comment by garrying** [comment]
Update: Regrouped with Marlo, and she's on board to collaborate. Thinking we'll be doing weekend sprints on the deliverables.

**Comment by dcwalk** [comment]
We have a plan! and a designer! 🎉
