### ISSUE TITLE
Ournetworks.ca Updated Design APR

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#27]
Confirmed drop-dead date of **APRIL 21** with the following goals:

## April 21 Goal
- [x] Logo
  - [x] SVG (B/W)
  - [x] PNG
  - [x] EPS (??)
- [x] Refreshed look & feel
  - [x] Social media image (`og:image`): `1050x550 pixels` (PNG or JPG)
  - ~Final content~
  - [x] Desktop
  - [x] Mobile
- [x] [First Phase Content **APR 30**](https://hackmd.io/s/S1mTYBcsM#), in https://github.com/ournetworks/ournetworks.ca/pull/19
  - Venue details (Sprint, Conf)
  - Sprint structure
  - Community Billet details
  - FAQ/Logistics

## Second Phase Content **MAY FIRST WEEK** and Third Phase Content **MAY MID**

In #39

**Comment by dcwalk** [comment]
Hey -- I don't think the Registration is a April 21 requirement -- we won't have met again and have time to implement, I think other elements from the content in #39 can and should be up tho!

**Comment by garrying** [comment]
Marlo had additional thoughts on the logo; we think this revised version feels better more resolved. Are we okay with moving forward with this? @dcwalk @benhylau @patcon
![logo](https://user-images.githubusercontent.com/227587/39681386-e76f85ca-5177-11e8-8bf8-0851e621abf6.png)

**Comment by benhylau** [comment]
I quite like the revised version. Also wonder how it'd look with more than 2 slashes.

I think I know what @dcwalk means, but that imbalance also works to differentiate the `://` from the text so when I read it, I read `our networks`, so it kinda works out.

**Comment by garrying** [comment]
With more than 2 slashes, and the right version is with height matched to the "t":
<img width="949" alt="screen shot 2018-05-07 at 11 57 21 pm" src="https://user-images.githubusercontent.com/227587/39737320-7f162c1e-5252-11e8-81c4-1db1876c07fd.png">

To me, the right version reads better as slashes.

@dcwalk I think the different colour treatments will work the same way with this graphic for swag and printed material if we decide to do that. Having more than two slashes seems to help for that treatment.

**Comment by dcwalk** [comment]
Agree, I'm sorry for blocking on this. My pref in order:

1. right-hand side
2. 2 slashes https://user-images.githubusercontent.com/227587/39681386-e76f85ca-5177-11e8-8bf8-0851e621abf6.png 
3. left-hand side

**Comment by garrying** [comment]
Closing. Nice to see everything coming together!
