### ISSUE TITLE
Develop sprints structure

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#29]
This seems like it needs to include:
- how to say you are interested
- identifying project lead
- whether there is some process that should happen at 2-day conf

analogues are pycon sprints and assemblies at congress

**Comment by benhylau** [comment]
Appended to: https://docs.google.com/document/d/14-N79UdKsayX995NPaNj4a2snVqs3aP2rFS2MfKoHVI/

**Comment by dcwalk** [comment]
Moving the first draft from the CFP ^^ here:

Sprints
Modelled after PyCon Sprints, we are running 3 days of Sprints following the 2-day conference. Sprints are opportunities for participants interested in a particular project to come together for intensive learning and development in a true Do It With Others (DIWO) environment. The goal is to make friends and build lasting relationships through working together to build features, fix bugs, polish documentations, hack prototypes, and share knowledge.

Dates: July 16-18

Propose a Sprint: Anyone can propose a Sprint before or throughout the conference days. It is encouraged that if a new idea comes up during the conference, and you feel a Sprint may be the right format to test / kickstart the project, that you will pitch a Sprint for it. Pitching a Sprint is very simple. Find our Sprints page, add a short description about your idea with the following information:

Sprint lead with contact email (e.g. @benhylau name@example.com)
Name of your project with a link, followed by a brief description of the Sprint objectives
(e.g. Toronto Mesh is a local mesh network initiative in Toronto. From 10am to 1pm on July 16, there will be introductory presentations about ongoing projects by the community, but anyone can pitch a presentation throughout the sprint. The first two days will be focused on setting up networks and services on Toronto Mesh software, and the last day to polish our documentations to address all the friction points encountered.)

**Comment by dcwalk** [comment]
On [2018-02-24 Call](https://hackmd.io/s/HkXytz1dG) call we talked about Sprint formatting, might try to launch in sync with Website Relaunch #27 or CFP deadline **APRIL**

**Comment by dcwalk** [comment]
RE: process, mentioned having it update as people submit their ideas (using PR to master publish workflow?)

**Comment by dcwalk** [comment]
A couple resources from pycon:
- https://us.pycon.org/2018/community/sprints/
- (and support for new sprint proj: http://opensource-events.com/#getting-your-open-source-project-ready-for-new-contributors)

**Comment by dcwalk** [comment]
This has happened! will land shortly in: https://github.com/ournetworks/ournetworks.ca/pull/19 (tho we may want to PR a .md with the deets in this repo after
