### ISSUE TITLE
finalize organizing committee

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#3]

**Comment by dcwalk** [comment]
Hey @jkms @benhylau @garrying glad that we'll all be working together on this! We'll use this project board to coordinate planning and tasks for the 2018 version, and @garrying has already rocked taking the lead at transferring over the website (https://github.com/ournetworks/ournetworks.ca)

@jkms are you based in Toronto?

**Comment by jkms** [comment]
@dcwalk 'Fraid not. Vancouver. Trying to organize things on the west coast :)

**Comment by dcwalk** [comment]
kk, @benhylau is gonna be .cat for most of the planning too. I think it'd be nice to aim for one more Toronto-based organizer to round things out.

**Comment by dcwalk** [comment]
I've done some initial asking around and had tentative maybes, but no additional people join in

**Comment by dcwalk** [comment]
Hey @patcon! Here is where we're coordinating :) 
Gonna close this for now, but we've gotta talk about it at our first call #17
