### ISSUE TITLE
Host a micro internet yami-ichi as our kick-off event?

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#30]
See: http://yami-ichi.biz/ and http://yami-ichi.biz/organize/

I'm wondering if this is even possible, but what if the opening night was a yami-ichi? 

"Internet Yami-Ichi, a flea market where people share and buy "internet-related" things,"

```
S*%t happens. Didn't used to. Like when some small off-handed private comment turns into an SNS flame war. Or worrying about not getting enough “Likes”. The Youtube videos you can't watch anymore because somebody complained. Or the apps you can't play because they were rejected by Apple. Once upon a time, the Internet was supposed to be a place for "liberty". Nowadays it's so uptight.

So let's turn off, log-out, and drop in, on the real world. The Internet Yami-Ichi is a flea market for “browsing” face-to-face.

Take your own Internet liberties* here, with us.

* But no dangerous or illegal goods, please! This black market wants to remain free and useful!
```

edit: mumble mumble Club Mate: http://www.clubmateontario.com/locations
---
edit2 (real one):
- from our call 2018-03-24 we identified considerations:
  - Vendor/attendee ratio is important! Likely can't just be conf attendees and our friends, needs to be broader
  - Connect to TMAC and Vector/Interaccess community? 
  - Things like tabling fee, entry fee important to understand
  - Will need a separate call (timeline?) 

and next steps:
  - [x] @dcwalk ask F/V about whether they would be interested in serving as a space (no confirmation)
  - [X] @dcwalk and @ana tour TMAC 😍 
  - [x] @dcwalk / @ana0 fashion this as a coherent pitch to approach co-organizers, 
  - [x] @ana0  email TMAC Tues April 10
  - [x] Draft budget (draft with other budget)
  - [x] ADD DEADLINES TO CALENDAR (done, and first issues to track in github #44, #45, #46

**Comment by dcwalk** [comment]
Fuel to the fire, our kickoff is July 15: 

- Vector Festival runs July 12-15, 2018 (http://vectorfestival.org/)
- Interaccess has a new space? Maybe we could collaborate?

**Comment by benhylau** [comment]
Our kickoff is 13, no? https://github.com/ournetworks/2018/issues/2#issuecomment-355753460

**Comment by dcwalk** [comment]
yeah. I just typod that.

**Comment by dcwalk** [comment]
No decisions from F/V, I'm wondering if we could maybe reach out to TMAC in parallel? 

Maybe we could schedule a tour for next week (Apr 10) or the weekend (Apr 7)? 
@ana0 are you also able to join
https://www.tomediaarts.org/space-rentals

**Comment by nucell** [comment]
Great idea, let me know if I can help.
Maybe get Vector to book this artist: https://roos.gr/ . The Black Box Bellagio or Google Consulate would be a nice overlap between events.

**Comment by ana0** [comment]
Seems reasonable to me to close it

**Comment by dcwalk** [comment]
okie!
