### ISSUE TITLE
advertise CFP!

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#34]
We should send off the CFP, some places, please edit this list, add as checked-off once done!:

- our toronto networks
  - [x] tomesh
  - [x] hacklab.to
  - [x] civic tech
    - [x] in person
    - [x] slack
    - [x] calendar
  - Toronto Students
    - OCAD
      - [X] Digital Futures
      - [X] Grad Students, Student Union (?)
    - UofT 
      - [X] U of T decentralized
      - [x] CSSU
    - York
       - [X] WISE
       - [X] Engineering SU    
    - Ryerson
       - [X] CSCU 
    - [X] Seneca
    - [X] George Brown
- other mesh projects:
  - [X] People's Open
  - [X] Meta Mesh
- international:
  - [x] battlemesh
  - [x] APC comm. network letter (@dcwalk)
  - [x] IFF newsletter and website (@dcwalk submitted)
- [x] twitter (tomesh, us)
- [x] key speakers/groups

**Comment by patcon** [comment]
- Sam McGarva and Christopher Pandolfi of Department of Unusual Certainties: [tweet](https://twitter.com/patconnolly/status/983194965646819330)

**Comment by dcwalk** [comment]
call closes tomorrow, think this ship has sailed! 👋
