### ISSUE TITLE
Official abbreviation of event name

### ISSUE THREAD

**Issue by patcon** [ournetworks/2018#35]
Saw that we're using SoON as our abbrev. I saw it in my inbox, and thought they were for SoONCon, which is a defunct group that organizes hackers-/maker-spaces in Southern ONtario: http://sooncon.ca/

It's likely no biggie. But made me wonder whether there's been an intentional decision yet, considering context clues, hashtags, etc.

Possibilities:

1. Mesh:SoON
2. SONets (pronounced like "sonnets" out loud?)
3. others?

**Comment by dcwalk** [comment]
Good call @patcon -- I think we actually have two namespaces we straddle:

SoON
- seems only internal use (on that form signup?)

ournetworks
- website
- github
- (I think I imported this to DO)
- 2017 hashtagging was almost all #OurNetworks 

Okay, bad at this but gonna try some minimal feels/facts
🔍 SoON is missing a lot of context as a abbrev/hashtag
🔍 #StateofOurNetworks is a long hashtag
❤️ I love the full name "State of Our Networks" (am I only one?) as I think it shifts the emphasis in all the "State of the X" by replacing the the/our. 
❤️ "Our Networks" feels like it captures the most important part of that ☝️ shift

I don't have a proposal, except that it seems like we might conciously avoid the abbrev. for external use?

**Comment by patcon** [comment]
:heart: I really love #OurNetworks too!
+1 on everything else

I'll prob just try to stay consistently with OurNetworks, external or internal :)

**Comment by dcwalk** [comment]
Okay, why don't we make that call then? I've added a note to the readme: https://github.com/ournetworks/2018/commit/2563e0e4c918073f761ce8ae2f612c837480069f

I'm feeling like we are okay to close this, will do so if I don't hear anything shortly :)
