### ISSUE TITLE
finalize swag goals APR

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#36]
Brainstormed in our **2018-03-10** call:
- T-shirts
- Stickers (smaller!)
- Buttons (could do at cost, @dcwalk has access to a button maker)
- (maybe) Tote (@dcwalk only pro-tote)

Extras to consider:
- Badges? see @patcon https://trello.com/c/3aGgKVrj/62-investigate-badge-like-sticker-sheets

**Comment by garrying** [comment]
Confirmed in #36
