### ISSUE TITLE
advertise *registration* MAY

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#38]
We should send off the registration, some places, please edit this list, add as checked-off once done!:

- direct link to ticketing: https://www.brownpapertickets.com/event/3447058
- our website: https://ournetworks.ca/conference/ and https://ournetworks.ca/swag/
---

- updates list
  - [x] updates email
  - [x] program launch email
- [x] postering
  - [x] Steamlabs (ben)
  - [x] YLab Maker Space (ben)
  - [x] Fort York Library (ben)
- [ ] previous our networks folks (2017)
- [ ] our toronto networks
  - [x] tomesh
  - [x] hacklab.to
  - [x] civic tech
    - [x] in person
    - [x] slack
    - [x] calendar
  - Toronto Students
    - OCAD
      - [ ] Digital Futures
      - [ ] Grad Students, Student Union (?)
    - UofT 
      - [x] U of T decentralized
      - [x] CSSU
      - [x] Engineering
    - York
      - [x] Engineering SU    
    - Ryerson
      - [x] CSCU 
    - [x] Seneca
    - [x] George Brown
- other community networks/mesh projects (ben)
- international:
  - [ ] battlemesh
  - [x] APC comm. network letter
  - [x] IFF newsletter and website 
  - [x] GAIA (done by someone else!)
- [x] twitter (tomesh, us)

**Comment by ana0** [comment]
Regarding registration: are we suggesting a "corporate" rate?  Or like a "pay us more than the actual ticket price because you have the money" rate?

**Comment by dcwalk** [comment]
I think we should consider it @ana0 ! The only thing we've discussed RE: registration is a scholarships option

**Comment by dcwalk** [comment]
Okay, registration up and an email sent off to those subscribing to updates. We are in good position I think, just need to bring that language to a postup #43 and roll out on email advertising too

**Comment by dcwalk** [comment]
Agreed on weekend to do final push. Closing now b/c sending the final email: https://github.com/ournetworks/2018/blob/master/advertising/email-selling-out.md
