### ISSUE TITLE
Identify ournetworks.ca 2018 content/info architecture

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#39]
In part to support #20 and #27 we should finalize our sense of the content that needs to be up in the 2018 section (and start drafting/pulling together!

## [First Phase](https://hackmd.io/s/S1mTYBcsM#): https://github.com/ournetworks/ournetworks.ca/pull/19

```
. Home Splash 
├── 2017  ✔︎
├── 2018  ✘ (same as HOME until 2018 ends)
│   ├── About
│   ├── Conference
│   ├── Sprints
│   └── Visiting Toronto (Community Billets, Navigating Toronto, Venue Accessibility)
├── Yami-ichi
└── Code of Conduct  ✔︎
```

  - [x] Sprint
  - [x] Venue details (Sprint, Conf)
  - [x] Yami-ichi
  - [x] About
  - [x] Visiting Toronto
    - [x] Community Billet details
## Second Phase Content MAY SECOND WEEK

```
. Home Splash (Registration)
├── 2017  ✔︎
├── 2018   ✘ (same as HOME until 2018 ends)
│   ├── About ✔︎
│   ├── Conference (Program Teaser + Registration) ✔︎
│   ├── Sprints ✔︎
│   └── Visiting Toronto ✔︎
├── Yami-ichi (Vendors)
└── Code of Conduct  ✔︎
```

- [x] Registration (@dcwalk: second wave of May launch?)
- [x] Venue details (Kickoff)
- [x] Call for Yami-ichi vendors Kickoff
- [x] "Keynote Speakers"

## Third Phase Content **MAY END**

```
. Home Splash (Registration)
├── 2017  ✔︎
├── 2018   ✘ (same as HOME until 2018 ends)
│   ├── About ✔︎
│   ├── Conference ✔︎
│   │      ├── Program ✔︎
│   │      └── Swag ✔︎
│   ├── Sprints ✔︎
│   └── Visiting Toronto  ✔︎
├── Yami-ichi (New Look)
├── Sponsors
├── Swag (under conference)
└── Code of Conduct  ✔︎
```

- [ ] Yami-ichi new look
- [x] Program/Schedule

**Comment by dcwalk** [comment]
Added the draft (above) from a cleaned up drawing here:

![20180408_184809](https://user-images.githubusercontent.com/4692834/38473451-490b8674-3b5e-11e8-9dcd-3569b69e0da7.jpg)

**Comment by dcwalk** [comment]
I'm going to check off the first phase seeing no comments? We can move this to a PR on the website repo to finalize actual content!

**Comment by dcwalk** [comment]
Hey @benhylau -- can you take a look at the draft Sprint page content: https://hackmd.io/s/S1mTYBcsM#, I moved over and slightly adjusted the content you drew up in the CFP. 

We need to think about the best way to manage this and be a little more descriptive in the text, are we gonna have people PR a repo? which one? (website directly?)

We could add in the venue details actually for Conference + Sprint too!

**Comment by benhylau** [comment]
I think PR the website repo directly is fine if we put that Sprint table up.

**Comment by dcwalk** [comment]
So I think we've launched the second phase: registration, program highlights! (A little behind on yami-ichi)

**Comment by dcwalk** [comment]
We've done all of this! A re-launch of yami-ichi needs to happen, but I figure we're safe to close
