### ISSUE TITLE
Create day-of signage

### ISSUE THREAD

**Issue by patcon** [ournetworks/2018#40]
## To Do (moved to top after co-work sesh!)

- [x] Decide what signage dimensions we want laser etched.
  - [x] podium signage (~32" max x ~20" max)
- [x] Decide what signage dimensions we want printed.
  - code of conduct (handled in #105 )
  - recording notification (handled in #105 )
  - spare direction details (handled in #105 )
  - chart paper sprints
  - chart paper afterpart(ies)
- [x] Create SVG images of signage.
- ~Confirm that Tool Library laser cutter usage is still free on open house night.~
- [x] Ask Zach about laser etching printers
- [x] research laser printing options (hacklab lives!!!)
- [x] Buy n+1 plywood sheets, n being the number we need (in case of laser bed slips).
- [ ] Confirm with @alexaca79 details of borrowing easels.
- [ ] Pick up easel stands.
- [x] Print the signage.

---

Here are some statements -- :mag: facts, :heart: feelings, and :bulb: ideas -- about this task:

### Laser cutters

1. :mag: CodeAcross has extra easel stands (@alexaca79 am I right?)
1. :mag: @zacharydonsky can either make these for us or help us make them.
1. :mag: Laser cut signage seems super-cheap.
1. :mag: HackLab has a laser cutter.
    - 1x2' cutting bed
    - FREE
1. :mag: @patcon and @zacharydonsky are HackLab members
1. :mag: Tool Library [has a laser cutter](https://torontotoollibrary.com/laser-cutter-tool-inventory/)
    - 2x4' cutting bed
    - $15 setup fee
    - $1/min for tool library members ($55/yr)
    - Material: $2/sheet -- 
    - FREE for makerspace members ($100/mo)
    - FREE makerspace access 7-10pm for open house (incl lasering according to Zach)
1. :mag: Tool Library requires a laser cutting course.
1. :mag: @zacharydonsky has already done the course.
1. :mag: @dcwalk is a tool library member -- confirm?
1. :mag: @zacharydonsky can get wood from his school for very cheap :)
    - Example: 12x24" sheet of 1/8" for $0.75
1. :mag: Test runs can be done with free scrap.
1. :mag: Laser bed can slip, and ruin the run.
1. :mag: We can etch on both sides of wood if need be.
1. :mag: 1/8" plywood sheets are fairly fragile to transport.
1. :heart: I feel that even if they broke or had prints on both sides, it would still fit the punk aesthetic :)

### Misc

1. :mag: @avWuff at HackLab owns a giant printer that prints from rolls.
1. :mag: @avWuff says it's broken: "All the ink is expired and it clogs constantly"
1. :heart: I feel that brokenness could contribute to the punk aesthetic.
1. :mag: HackLab owns a vinyl cutter.
1. :mag: @patcon has never used the vinyl cutter.

.

1. :heart: I feel excited to do laser etching, as we it will be nice to have Zach's help.

**Comment by dcwalk** [comment]
Easels + laser etching sounds pretty great. Part of me thinking it'd be lovely to use on paper for some interesting nametags too!

**Comment by dcwalk** [comment]
Hey @patcon -- do we still need the easel part of this? It seems like probably not, tho they might be helpful for the breakout sessions (we will have chart paper)

**Comment by dcwalk** [comment]
Also! We'll want this stuff on Friday (Easel and signage) I think for the yami-ichi. Is that an issue?

**Comment by dcwalk** [comment]
Hey @patcon, I wasn't sure where you are at and was trying to backroom help so I drafted an attempt of an 8.5 x 11 8-up for the nametag badges. Literally 0 issue if you don't need 'em!


<img width="822" alt="screen shot 2018-07-12 at 9 00 09 am" src="https://user-images.githubusercontent.com/4692834/42634765-21b6dc06-85b2-11e8-8929-f9006129a1f1.png">

[our-networks-badges-draft.zip](https://github.com/ournetworks/2018/files/2188686/our-networks-badges-draft.zip)

**Comment by garrying** [comment]
@patcon Following up on your request for a MakerDAO sponsor logo comp:
![screen shot 2018-07-12 at 10 48 38 pm](https://user-images.githubusercontent.com/227587/42669880-df397cac-8625-11e8-8eb3-abfb6415e5e2.png)

[our-networks-shirts-tote_design-2-july12.zip](https://github.com/ournetworks/2018/files/2191078/our-networks-shirts-tote_design-2-july12.zip)

**Comment by dcwalk** [comment]
THESE ARE SOOOOOOO BEAUTIFUL ❤️
