### ISSUE TITLE
Swag Design

### ISSUE THREAD

**Issue by garrying** [ournetworks/2018#42]
# May 26 Goal (WIP):
- [x] Confirm swag goals (#36)
- [x] Stickers
- [x] T-Shirts
  - With sponsor logos
- [x] Buttons
  - [x] 1"
  - [x] 1.25"
- [x] Tote Bags (stretch)
  - With sponsor logos

**Comment by dcwalk** [comment]
Hey @garrying can we say we've confirmed our swag? It looks like we have the goals right here!

Also, can we edit to indicate that Tote Bags and T-Shirts would have sponsor logos?

**Comment by dcwalk** [comment]
Hey I was thinking on this -- Is it unreasonable to imagine mocking up some of these to co-launch with registration?

I think our best chance for gauging numbers too would be to have those being purchased up to the event?

**Comment by garrying** [comment]
@dcwalk Is the idea that we'd be showing swag with registration? I think the stickers, and pins can be hashed out with registration. T-shirts and totes I'm less sure about since we're in the middle of collecting logos and it might take a few design iterations before we place an order.

Also, #43 seems like something we can move on, maybe in parallel with this?

**Comment by dcwalk** [comment]
Can we mock up the logo area? I'm not saying we put the order in
beforehand, but that rather we get a sense for numbers.

Do you not anticipate us finalizing a design in the next week? I'm nervous
if we don't include on registration we won't sell enough to hit the scale
sweet spot. $20-25 is the range of price points I've hit before

**Comment by garrying** [comment]
These are drafts of what I had in mind. Looking for input on how to frame sponsors on the back. I also included a version with the website colour to see if we want to source a comparable colour:
![ournetworks-shirt-mock-ups](https://user-images.githubusercontent.com/227587/40284818-76adffa6-5c62-11e8-8625-5aba7cc7ab59.png)

Art detail:
![ournetworks-shirt-art](https://user-images.githubusercontent.com/227587/40284822-7b15acce-5c62-11e8-8f6f-bc4d810acce0.png)

**Comment by dcwalk** [comment]
OMG THESE LOOKS SO GOOD!!!

**Comment by dcwalk** [comment]
📣 this just in: glow in the dark totes

**Comment by garrying** [comment]
- buttons: Moved them off the edge, and bumped their size
![screen shot 2018-05-22 at 10 05 10 am](https://user-images.githubusercontent.com/227587/40367726-12b744c0-5da8-11e8-8961-7d30cb97d9bf.png)

- stickers: Draft of a 2018 version (needs space tweaking), and ported the logo into a rectangle format
![screen shot 2018-05-22 at 10 05 24 am](https://user-images.githubusercontent.com/227587/40367995-af26625a-5da8-11e8-97c8-ce6efa379698.png)

**Comment by dcwalk** [comment]
Okay so I have access to a 1.25" button maker, will aim to buy supplies here: https://peoplepowerpress.net/products/everything-for-your-1-1-4-button-maker?variant=972677980

**Comment by dcwalk** [comment]
Hey @garrying, I'm gonna plan to do test prints for the buttons by June 24/25, can you help have them laid out in a printable way by then?

Basically I will have to cut a sheet of paper into strips narrower than 2-3" to feed thru a punch, will need a bit of margin but not too much! Would be good to get as many as possible on a page to reduce cost as we'll have to pay to print. 

I'll be printing 125 each of 1.25" and 65 each of 1"

![100-tecre-punch_1f44c5d6-8830-426d-8efa-aa7aaadcbeaf](https://user-images.githubusercontent.com/4692834/41076462-b7b9803a-69df-11e8-9a63-00ada2334bab.jpeg)

**Comment by benhylau** [comment]
![screen shot 2018-06-07 at 1 58 37 am](https://user-images.githubusercontent.com/2261308/41081083-78051770-69f7-11e8-8f2e-32c5fb3ea937.png)
![screen shot 2018-06-07 at 2 06 06 am](https://user-images.githubusercontent.com/2261308/41081084-7815316e-69f7-11e8-84ea-4b8b956c385c.png)

Want to do rolls? They are the cheapest. Quality is pretty good I have ordered before.

**Comment by benhylau** [comment]
Shall we select 3 sticker designs and print 200 of each, then make 50 sticker sheets, each includes all 6 styles: 

![screen shot 2018-06-07 at 2 54 09 am](https://user-images.githubusercontent.com/2261308/41083495-52f0dd5e-69ff-11e8-8dee-5e3fca5c4719.png)

**Comment by dcwalk** [comment]
@benhylau Can we do more? Is there a way to do 100 of each in square, cirle and rectangle?
I guess I don't know the value of the sticker sheets (like would we distribute them that way?)

**Comment by dcwalk** [comment]
Ah, that is a big quantity discrepancy. Your call!

Would we be able to fit all 6 designs on 4x6? I think it might be tight with the rectangle designs

**Comment by benhylau** [comment]
Because 100 -> 200 is a small price jump for the same style. The sheet can be custom sized without not much additional cost, 4x6 is just a sample.

Some people are going to want all styles of stickers, so they can take a sheet. After the conference we'd probably distribute stickers in other conferences / events, and we probably prefer quantity there, so focusing on 2-3 styles and taking advantage of the 200 pc rate seem a reasonable choice?

**Comment by benhylau** [comment]
Let's aim to place the order for shirts + stickers the coming Friday June 15. We need the following:

- [ ] Final list of sponsors and logos for print @ana0 @dcwalk 
- [ ] Final art in SVG @garrying
- [ ] Final draft order for shirts and totes @benhylau
- [ ] Final draft order for stickers @benhylau

**Comment by dcwalk** [comment]
Ugh, sorry @benhylau one more thought on stickers: I would really really dig if we printed large quantities of the two circle stickers, as they are the most distinct (and neat!)

**Comment by benhylau** [comment]
It'll look something like this, but a little more than what I'd expect to spend on stickers. Thoughts?

![screen shot 2018-06-10 at 12 43 52 am](https://user-images.githubusercontent.com/2261308/41198378-57982ba6-6c47-11e8-869d-b7fa0d58f0ad.png)

**Comment by garrying** [comment]
That does seems a bit more than I'd expect. Deferring to you two on quantities.

@benhylau I spotted weird shape issues with SVG outputs so I opted for AI (preferably) and EPS, which should be fine for Sticker Mule. We should take a look at a proof when they have it ready.

Vector files here:
https://github.com/ournetworks/artwork/pull/3

**Comment by dcwalk** [comment]
Ugh sorry, I'm not communicating well -- I didn't mean to up the amts that high, I just meant, could we aim for like 200 of each, rather than 200 of one design, and then the other only on the sticker sheet (sorry, words failing me these last few days)

**Comment by benhylau** [comment]
How about this? The sheets will contain the 4 box styles, and we'll print 500 of one of the circles and 200 of the other. I hope to keep things under USD 250. This also gives us 900 stickers in total.

![screen shot 2018-06-11 at 1 03 03 pm](https://user-images.githubusercontent.com/2261308/41246052-d949ead2-6d77-11e8-951c-c9d11ee06ea8.png)

**Comment by dcwalk** [comment]
<img width="737" alt="screen shot 2018-06-11 at 1 57 32 pm" src="https://user-images.githubusercontent.com/4692834/41248676-c0cd4546-6d7f-11e8-801b-36946d64b54c.png">

**Comment by garrying** [comment]
@benhylau updated square sticker dimensions in https://github.com/ournetworks/artwork/pull/3/commits/458b8341e21d6bfed1e0411a37571d318b475a92

**Comment by dcwalk** [comment]
I think we're good for swag designs (yaaay!) just ordering in #74

**Comment by dcwalk** [comment]
@benhylau is there further design work that needs to happen?

**Comment by benhylau** [comment]
Now with the sponsorship from Sticker Mule, I propose printing this:

![screen shot 2018-06-18 at 5 36 33 pm](https://user-images.githubusercontent.com/2261308/41563642-36f7b3fc-731e-11e8-8a32-58761a843ff6.png)

500 x Circle Black
300 x Circle Accent
300 x Square Black

@garrying we need one sticker sheet design with Square Accent + the two Rectangle designs, spaced 0.25" apart, on a single 4.75" by 2.25" canvas.

**Comment by benhylau** [comment]
Thanks @garrying
