### ISSUE TITLE
Kickoff: Reach out to Vector Festival

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#45]

**Comment by ana0** [comment]
Have reached out informally to gauge interest - will follow up with a more formal email if they're interested

**Comment by nucell** [comment]
One of the Vector Festival artists may be willing to exhibit at the Yami-Ichi:

http://nadinelessio.com/ is interested in discussing the requirements for an installation of http://fortunetasker.com/

Who is coordinating Yami-Ichi vendor / exhibitor spots?

**Comment by ana0** [comment]
Hey!  I know Nadine and this is a great fit for the Yami-ichi :)  
You can pass along this form (it goes to us and the Bit Bazaar folks) https://2018.bitbazaar.world/ and questions about installation requirements can go to orga@ournetworks.ca

**Comment by dcwalk** [comment]
Awesome! I'm thinking we could close this as the reaching out has happened, but also thinking any further convo can be in #83
