### ISSUE TITLE
Firm up financial structure MAY 7

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#48]
Need to decide on strategy for holding funds for 2018, on [April 28 call](https://hackmd.io/s/ryBqWmO2M#), 2 paths were discussed:

- personal invoice sooner (dcwalk) via sole proprietorship, named company, etc...
- wait on group and invoice via OCF Canada (patcon)

Will act on this before **May 6**

**Comment by patcon** [comment]
## OCF Canada Updates

- OpenCollective is willing to sponsor us $1000 to fund bootstrapping OCF Canada
- They are willing to match funds dollar for dollar for the next $1000
- @dcwalk and @patcon meeting on Thurs, May 3 to figure out plans
- @patcon meeting with sprins on morning of Thur, May 3.

**Comment by dcwalk** [comment]
Update: We've opened at Community Acct with Alterna Savings, this should be ready on Monday, May 7 for invoicing

**Comment by dcwalk** [comment]
We got this! @benhylau sending off first invoices tomorrow, we are tracking in our Sponsorship Pipeline doc
