### ISSUE TITLE
Select Registration Platform

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#52]
We're talked about this a few times but wanted to start surfacing options (with my assessment of some pro/cons:

- [Eventbrite](https://www.eventbrite.ca/en_CA/l/conferences/) **4.5% + CA$0.59/ paid ticket*** (to support selling gear/multiple ticket types/custom form)
  - Pros:
    - Familiar for attendees (esp. Conf/Tech in Toronto crowd)
    - Straightforward for organizers
    - Organizers support: check-in app, analytics (?), mobile ticketing, etc...
  - Cons: 
    - [Collect a lot of data](https://ourdataourselves.tacticaltech.org/posts/24_events_conferences_1/) that they use elsewhere, classic BM
    - I know nothing about their politics, workplace culture, etc...
- [Brown Paper Tickets](https://www.brownpapertickets.com/) **organizers: free --> 2.5% (if we use [paypal/own cc](https://www.brownpapertickets.com/pricing.html))**, attendees: CA$0.99 + 3.5%**
  - Pros:
    - Potentially inline with our values: social impact (maybe non-profit? a little unclear) env. responsibility)
    - Organizers support: check-in lists, scanning app, mobile tickets, free ticket mailing (?!)
    - One level of costs which covers everything (vs. Eventbrite), support for multiple tickets, additional swag etc...
  - Cons: 
    - Only money after event if using their payment processor, 2.5% fee if we use our own, or paypal, for instant money
    - No choice about absorbing vs. passing on ticket cost
    - less name recognition? esp. for tech stuff?
    - Apparently interface a little cumbersome (I took a peek, def. not super clean. I have bought tickets using this before and found it fine 🤷‍♀️ )
- Transparent Finance Platforms (e.g., [OpenCollective](https://opencollective.com), [Liberapay](https://en.liberapay.com/explore/organizations)) OC: **10% for fiscal sponsorship, 2.9% + $0.30 per transaction**
  - Pros:
    - Potentially more aligned with our values
    - Potentially addresses other needs (transparent finances)
  - Cons: 
    - Additional overhead in costs 
    - May need to adapt to have work for event registration (Liberapay more about recurrent donations, OC only has partial/minimal ticket registration)
    - Will have to think through adopting a model of public registration (not that the model is a con, but I would want to talk about it)
- Self-host (e.g., [BridgeTroll](https://www.bridgetroll.org/about), [Attendize](https://www.attendize.com/)) **variable, payment processor fees** example: [Stripe](https://stripe.com/us/pricing) is  2.9% + C$0.30
  - Pros:
    - Potentially more aligned with our values
    - Total control!
  - Cons: 
    - Total control: we have to host, hook in with payment process
    - Implementation :((
    - May not support an edge use case we have

**Comment by dcwalk** [comment]
We discussed this at the [May 13 meeting](#), our decision was:

- Use Brown Paper Tickets for our registration (@dcwalk to set up)
   - planning to have multitple levels of tickets: reg, supporter, my company can pay
   - coupon codes for scholarships
   - swag integrated!
- Set up Stripe integration, because batch processing of funds (before the event) is probably ideal

@ana0 and @patcon we wanted to ping you on this to see if you have any thoughts? Our aim is to finalize by **end of this week**, e.g., May 18

**Comment by dcwalk** [comment]
Okay so slight wrinkle: brownpaper tickets doesn't do Stripe integration :((( 
I think we can work with paypal and their credit processor if that works for folks?

You should all have an email with the registration sample

**Comment by dcwalk** [comment]
The pricing structure:


Ticket  | Cost | Desc. 
-- | -- | --
Reduced Cost Admission | CA$20.00 (CA$21.69 w/service fee) | If you are unwaged, a student, or otherwise in need of a reduced cost registration
Supporter Admission | CA$65.00 (CA$XX.XX w/service fee) | The cost to run this event is $65 per person, consider registering as a supporter to allow us to put sponsorship money 
Company Supporter Admission | CA$100.00 (CA$104.49 w/service fee) | Consider registering as a company supporter if your company is paying or you can be reimbursed for your registration. This allows us to offer reduced cost admissions as well as scholarships

**Comment by ana0** [comment]
Something like, "If you're unable to pay the reduced entry rate, reach out at email@email.com we have scholarship possibilities and are also looking for event volunteers, who will get full complimentary admission"

**Comment by ana0** [comment]
Or maybe just the volunteers thing, since I'm not sure scholarships are confirmed?

**Comment by dcwalk** [comment]
Yeah @ana0 ! We haven't yet hit the funding targes for a huge number of scholarships so a bit in flux but I don't think that should prevent us from being able to offer a couple! 

It feels really important to me.

**Comment by dcwalk** [comment]
We did this! https://www.brownpapertickets.com/event/3447058 (YAYAYAYAYAY!) closing
