### ISSUE TITLE
Research vendor for conference t-shirts and totes

### ISSUE THREAD

**Issue by benhylau** [ournetworks/2018#53]
This Issue will be used to collect vendor research information. See https://hackmd.io/s/r14h4mICf for requirements.

**Comment by dcwalk** [comment]
**t-shirts & totes**

- [Customink](https://www.customink.com/canada?pc=OTHER-143685) 
  - Last order was $19/shirt for 20 shirts. 2 colours front
- [tshirtguys.ca](http://www.tshirtguys.ca/)
  - **LOCAL**, no totes (maybe amenable?)
  - got a recco from a friend
  - can quote online
- [Sugarbomb](http://www.sugarbomb.ca/)
  - **LOCAL**, with totes and tshirts!
  - got a *wonderful* recco
  - need to contact for a quote

**stickers**
- [sticker mule](https://www.stickermule.com/)
  - Last order was $85 for 200 stickers incl. shipping
  - very happy!
- [StickerYou](https://www.stickeryou.com/)
  - Last order was $130USD for 500 stickers + 2 breakoutsheets of 10 stickers incl. shipping
  - Local
  - Force you to pay in USD and pay for shipping :((

**Comment by benhylau** [comment]
tshirtguys.ca
==========

## Shirt (based on single-colour front and back print)
Gildan G640: CAD 22.22 (12 MOQ), CAD 11.87 (36 MOQ)
Triblend 28.70 (12 MOQ), 21.22 (36 MOQ)

_* Variety of brands and colours. Most fall between the ones quoted above_
_* Can mix size and colour within limits_

## Print colour (based on single print area 36 MOQ)
2 colour: CAD 10.08
3 colour: CAD 11.53

## Pattern
- 12 in x 18 in per print area
- wrap around possible on certain shirt types

## Tote
Basic tote: CAD 10.71 (36 MOQ)

## Stickers
By signbros.ca partner

**Comment by garrying** [comment]
WIP Designs are in https://github.com/ournetworks/2018/issues/42

**Comment by dcwalk** [comment]
Moving offline convo here, we discussed:

- ordering in loose & fitted
- getting samples to confirm best tshirt feeling (Base Gildan can be rough, @dcwalk had luck with softstyle)
- needing to confirm if we can find that beautiful colour or do matching (is there a cost?)
- totes in single colour (one style)

**Comment by dcwalk** [comment]
To compare quotes moved to [spreadsheet](https://docs.google.com/spreadsheets/d/1Oq8rZfBgCwWL9KGu_gwxhPjXRYabKF4vFR1zQgR1k7I/edit#gid=0)

**Comment by dcwalk** [comment]
I'm going to close this in favour of #74, but please re-open if that is presumptuous of me!
Thanks for all the swag mountain climbing ⛰
