### ISSUE TITLE
Conf: Walkthrough of venue JUL 11

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#64]
Scheduled walkthru (in calendar) on Wed, Jul 11

Should talk with N. and do a walkthrough of space, in particular questions about the workshops and what is possible with that
---

- Registration Desk (and Swag desk)
  - We can set up inside the room
- Workshop/Breakouts
  - One room for 10 people, small screen
  - Main space has three screens and can be set up for a breakout area off from the main podium
- Accessibility
  - 8 steps with handrail up to elevator on Main (South) entrance
  - Barrier-free (North) entrance has a couple path options: 2 with medium grade from Adelaide; 1 over gravel from Spadina and back elevator) will require volunteer positioned on main floor to ensure access
- Washrooms 
  - 2 gendered multi-stall washrooms with access off the main space, 
  - an all-gender washroom we can use as well
- Security 
  - Need to supply list of names week prior
- Internet
  - Guest Wifi can be arranged
- A/V
  - cameras and speakers set up
  - three screens
  - podium with hookups (and podium mic)
  - 4 wireless mics + 1 roving (plush) mic
  - will do a separate walkthrough to finalize details

**Comment by Shrinks99** [comment]
I'd like to tag along on this if possible.  We need to know what AV equipment is available for the stream, what the outputs are and what the projector aspect ratio is so presenters can format their slides accordingly.

**Comment by dcwalk** [comment]
We did a prelim walkthrough, I'm adding the notes from the sesh above, but we also have a plan for a week before walkthru (incl. A/V testing) so I'm gonna keep this open for now

**Comment by dcwalk** [comment]
Updates based on Wed July 11:
- Registration Desk (and Swag desk) inside by front
- A/V
  - cameras and speakers set up
  - podium with hookups (and podium mic)
  - 4 wireless mics + 1 roving (plush) mic
  - Will use A/V podium, tested and expecting an email to confirm Jon
  - Mozilla loaner laptop as presenter laptop
  - Many extra power strips
- Internet
  - Guest Wifi open
- Workshop/Breakouts
  - One room for 10 people, small screen
  - Main space has three screens and can be set up for a breakout area off from the main podium
- Accessibility
  - 8 steps with handrail up to elevator on Main (South) entrance
  - Barrier-free (North) entrance has a couple path options: 2 with medium grade from Adelaide; 1 over gravel from Spadina and back elevator) will require volunteer positioned on main floor to ensure access
- Washrooms 
  - 2 gendered multi-stall washrooms with access off the main space, 
  - an all-gender washroom we can use as well
- Security 
  - Need to supply list of names week prior


- Yurko buying long HDMI cables x2 (~$40)

**Comment by dcwalk** [comment]
We had this! closing :))) adding the cables to the materials list in #98
