### ISSUE TITLE
Presentation Buffers

### ISSUE THREAD

**Issue by garrying** [ournetworks/2018#68]
- [x] 1080x1920 pixels (PNG or JPG)
- [x] Sponsor logos (ISOC, Protocol Labs, DappHub, MakerDAO, ConsenSys)
  - [x] In-Kind logos (Sticker Mule, Quantum Coffee, Tyfer Bakery)
  - [x] Venue Partners (Mozilla, Semaphore Research Cluster, TMAC)

@Shrinks99  aiming to do tonight (July 11)

**Comment by benhylau** [comment]
@Shrinks99 suggested we find out about the projector's aspect ratio, then have the slides in that as well as include that information in messaging to presenters.

**Comment by dcwalk** [comment]
From chat on 2018-Jul-26:

- One version will be OBS (template will need to be stored in this repo)
- One version for a desktop?

**Comment by Shrinks99** [comment]
Presentation buffers / stream graphics will be OBS scenes.  Can you elaborate on what is for a desktop?  Desktop wallpaper?

**Comment by benhylau** [comment]
OBS version will use the auto-rotating script. "Desktop" being the version that will be projected onto the screen, hopefully from a Mozilla desktop.

**Comment by benhylau** [comment]
Related https://github.com/tomeshnet/ipfs-live-streaming/issues/9

**Comment by Shrinks99** [comment]
Current stream graphics, will update with new ones based on @garrying and @dcwalk's  comments in https://github.com/tomeshnet/ipfs-live-streaming/issues/9.  Apologies for not doing that sooner!

[Stream Graphics.zip](https://github.com/ournetworks/2018/files/2178602/Stream.Graphics.zip)

**Comment by Shrinks99** [comment]
@dcwalk I am going to try to get all the graphics worked out tonight based on the feedback already given, I will post all assets in an updated 'Stream Graphics.zip' file and if things still need to be changed anyone with Illustrator should be able to do that on the off chance I am not able to.  Opening and closing remarks?  Do we need a special title card or something?

@benhylau The variables to use in OBS will be as follows:
`'currentpresenter'
'currenttalktitle'
'nexttitle'
'nextpresenter'
'nexttime'`

Do not include the ' !

**Comment by Shrinks99** [comment]
@garrying @dcwalk 
### Lower Third Options

![lower thirds](https://user-images.githubusercontent.com/5672810/42488030-9fcf7284-83d1-11e8-8907-4e9241468d19.png)

All feedback on the lower thirds from tomeshnet/ipfs-live-streaming#9 has been taken into account.  @dcwalk I agree on the picture in picture, we will be dropping the graphics for the presenter / slide scene.

**Comment by benhylau** [comment]
@garrying @dcwalk During our call we had a couple questions:

1. Should in-between slides rotate sponsor logos or have all of them in one slide?

1. What are the full set or sponsor logos that need to go on the slides? Whoever is on https://ournetworks.ca/sponsors/?

1. The DappHub logo is the only one without the organization name. We plan to put the text `Dapp.Org` (the preferred name by the sponsor) beside it. Let me know if there is any concern.

**Comment by Shrinks99** [comment]
### Between Presentations Scene

![sponsors-01](https://user-images.githubusercontent.com/5672810/42489941-e5e3bf28-83db-11e8-8ed6-b0c17da41694.png)

This is still very much a WIP, looking for feedback about sponsor sizing and placement.

**Comment by dcwalk** [comment]
@benhylau:

> 1.  Should in-between slides rotate sponsor logos or have all of them in one slide?

I think one slide for all sponsors, but maybe rotate that and a "Our Netoworks" slide?

> 2.  What are the full set or sponsor logos that need to go on the slides? Whoever is on https://ournetworks.ca/sponsors/?

Yes, I'd treat the website at the canonical source. We still need to add 2 logos for those in the works: Quantum Coffee (In-kind), Maker Dao (?? Tier 1 equiv. Maybe @ana0 has a sense of naming)

> 3. The DappHub logo is the only one without the organization name. We plan to put the text Dapp.Org (the preferred name by the sponsor) beside it. Let me know if there is any concern.

I think `Dapp.Org` added beside is fine, but also probably okay to leave it 🤷‍♀️

**Comment by benhylau** [comment]
I think adding the name is better because the way we requested name and logo may have given the impression that they will both appear together. On the website you can just click, but on a slide it'd probably be more useful to have `Dapp.Org` on there.

**Comment by dcwalk** [comment]
@Shrinks99:

👍 nice!

For Lower Third Options:

- I prefer the "B" design
- I strongly favour us keeping the same proportions on the `://` as we've used elsewhere, so your A/B designs:
<img width="157" alt="screen shot 2018-07-10 at 1 12 18 am" src="https://user-images.githubusercontent.com/4692834/42490456-592d693c-83de-11e8-85be-c4fa4d4129bd.png">
- I'd say no outline needed if this is a lower third

For Between Presentations Scene:

I'm not sure if I'm visually reading/interpreting correctly... but my first thoughts...

- I think one page for all sponsors, and ensuring we preserve the difference groupings as we do on the sponsor page is important
- We also committed to Tier 1 being "large" logos elsewhere in print and I think we need to carry that through here. I'd aim to keep them all on the same shelf (as in our website!)
- see my comments above RE: rotating
- see my notes above RE: anticipating 2 more logos

Neat to see this coming together!

**Comment by ana0** [comment]
Re: MakerDao - tier one is probably the right place - the vast majority of that sponsorship is going to the bit bazaar x yami ichi but it's significant enough I think we might as well put them in the tier 1 for conference branding

**Comment by benhylau** [comment]
- [ ] @Shrinks99 please use these variable names in OBS instead: 
    ```
    current_title: "Opening"
    current_presenter: "Our Networks"
    next_title: "Wireless Toronto"
    next_presenter: "Gabe Sawhney"
    next_time: 2018-07-14 10:00 
    ```
- [ ] @ASoTNetworks please test this out since I do not have a working OBS version (MacOS version cannot run python scripts): https://github.com/ournetworks/2018/pull/109
- [ ] @ASoTNetworks also test what happens if you set the path and then delete the file, then timer refresh kicks in and it can't open the file, what does OBS do?

**Comment by garrying** [comment]
@Shrinks99 
Lower Third Options:
- Option B is also my pick
- Think it'd be good to see it in context on next review!

Between Presentations Scene:
- Agree on one page for sponsors, rotating
- +1 to preserving the groupings (or at least the sizing)
- For layout, I think they will present well if we keep to rows
- Would be ok with bumping up the white space to accommodate the layout and more negative space around the logos.

**Comment by Shrinks99** [comment]
The Between Presentations scene is currently a single OBS scene which contains both sponsors and the time. speaker and presentation title for the next talk.  They aren't currently slated to be separate scenes but could be if you'd like.  I will try a vertical arrangement on the right half of the screen in order to do a better job of displaying sponsor tiers.

Option B it is, I will create a mockup using that one when I get home today!

**Comment by garrying** [comment]
@Shrinks99 Definitely prefer SVGs! But in some cases PNGs are the only files we have. Let me know if any are not display nicely. We can try sourcing higher res versions.

**Comment by Shrinks99** [comment]
Here are the final stream graphics as discussed today, I will create a PR after the stream in the 2018 artwork folder to ensure that whatever goes in there is 100% the version used in production (archiving is nice and all).  For now refer to this and whatever @ASoTNetworks has as the final files.

[Stream Graphics.zip](https://github.com/ournetworks/2018/files/2187070/Stream.Graphics.zip)

**Comment by dcwalk** [comment]
@Shrinks99 Great! can you reshare (and actually maybe just open a pr now that we hold off on merging...? with all the source/fonts etc.. included?

**Comment by Shrinks99** [comment]
I have seen this and will do it!

**Comment by garrying** [comment]
Closing this with https://github.com/ournetworks/artwork/pull/13 merged.

@Shrinks99 will follow up on adding the OBS JSON and mirroring the PNG assets in this repo.
