### ISSUE TITLE
Finalize Catering Plan JUL

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#70]
- [x] Order club mate (yami-ichi, vending)
  - [x] emailed for details
  - [x] delivered (to @dcwalk on THURS)
- [x] Book coffee breaks (Quantum)
  - [x] emailed for details
  - [x] finalize order
  - [x] deposit
- [x] Order Lunches (Regent Park Catering Collective)
  - [x] email for quote
  - [x] review quote
  - [x] finalize/order
- [x] Costco run (snack breaks, drinks, tea)
  - [x] price out menu (ish)
  - [x] book day (Thurs!)
  - [x] confirm amt to spend
  - [x] purchase (@benhylau on THURS)
- [x] Pedro snacks (pastries)
  - [x] @benhylau to ask
  - [x] confirm THURS
- [x] Purchase the things to eat on (snack plates, cups, cutlery, napkins)
  - [x] plates for breaks (250)
  - [x] cutlery (300 forks)
  - [x] too many napkins
  - ~plastic cups~

---

This can be a first week of July plan, we have the following commitments for both days for ~80 people and a tight budget:

- Morning ($1.9/person)
  - Coffee & Tea
  - Snacks
- Lunch ($9.5/person) <-- adjusted up after doing some budget shaping. this is still v. low
  - Non hot drinks
  - Boxes? 
- Afternoon ($1.9/person)
  - Coffee & Tea
  - Something Sweet

Some prelim thoughts:
- Could do a shopping trip to pickup our own morning snacks, afternoon snacks, and potentially lunch drinks to reduce costs
- Breaks then just order coffee from catering (and ask about sponsorship!)
- Lunch aim for something lunchbox-y (and ask about sponsorship!)

Nearby coffee:
- Quantum ?? https://www.quantumcoffee.io/
- Aroma $$ https://aroma.ca/
- Druxy $ https://druxys.com/

Nearby lunchboxes:
- The Goods $$ (10-15) ❤️ https://thegoodsisgood.ca/pages/catering
- Freshii $$ https://www.freshii.com/us/menu (Spadina & Richmond: 203-8456)

Sandwich/wrap platters:
- Pumpernickels Wraps $ (<10) https://www.pumpernickels.ca/
- Druxy $ (<10) https://druxys.com/
- Regent Park Catering Collective $ (<10) http://rpcateringcollective.tccld.org/menu/
  - Wraps $ 5.5 - 6.5 + tax
  - Appetizer (Vegetable Samosas + Falafel + Mandazi) $ 1.2 + tax

**Comment by dcwalk** [comment]
@benhylau what is news about pastries? :delicious: 😊

**Comment by benhylau** [comment]
I asked Pedro to let me know before Thursday morning. Basically tarts vs. brownies :)

**Comment by dcwalk** [comment]
This happened! I'm closing in favour of final discussion of outstanding items tonight at #117
