### ISSUE TITLE
Request room layout from venue JUL

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#72]

**Comment by dcwalk** [comment]
@benhylau can you confirm this has been done?

**Comment by benhylau** [comment]
For the conference part of the conference this is communicated to our venue partner and the space should be arranged by the time we do the walkthrough.

**Comment by dcwalk** [comment]
This was sent in, confirmed with jlin and n. that it was forwarded. I think there is nothing else we can do at this point 🤷‍
