### ISSUE TITLE
Order Swag (Tshirts, Totes, Stickers, Buttons)

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#74]
Chatted with @benhylau today, drawing on his work in #53, we have the following plan:

- [x] Order tshirts and totes *1 month out* (@benhylau) *$??* for 80-100
- [x] Order stickers (@benhylau) *$??* for 200
- [x] Order button-making supplies *June 24* (and make 'em) (@dcwalk) *~$187* for 500 mix 1", 1.25" (to make 200 costs *~$125*)
  - [x] pick up button maker
  - [x] pick up supplies

We have a [tshirt and tote spreadsheet](https://docs.google.com/spreadsheets/d/1Oq8rZfBgCwWL9KGu_gwxhPjXRYabKF4vFR1zQgR1k7I/edit#gid=0) for managing that order, we will add final costing to our [budget]()

**Comment by dcwalk** [comment]
@benhylau can you update here with the date you'll plan to order stuff by?
My sense is that we should confirm some things before:

- current vol'n shirt size
- orga shirt pref. _ size (and maybe free quota ;))

**Comment by benhylau** [comment]
@dcwalk @garrying @ana0 @patcon Please indicate shirt preferences https://docs.google.com/spreadsheets/d/1Oq8rZfBgCwWL9KGu_gwxhPjXRYabKF4vFR1zQgR1k7I/

For volunteers I think it's easiest if they pick a shirt at orientation, whichever one they prefer.

**Comment by dcwalk** [comment]
Don't we want volunteers to all wear the same design? That would be my preference (or at least, have them wear the 2018 one or something.

Also, we need to account for preorders

**Comment by benhylau** [comment]
@dcwalk I have no strong opinion on volunteer shirt styles. The 2018 in either colour is easily identifiable so it sounds like a reasonable choice :)

I don't think we need to specially account for pre-orders, but can use that as a guideline to see if our style/colour/size allocation is inline with demand.

Do you want to make adjustments to the order quantities currently listed on the spreadsheet or you think they look fine? So far we have very little data but it seems the 2018 style will be a hit and we could add more of those and make less of the General style.

**Comment by dcwalk** [comment]
This has been done! 
New issue for confirming we have swag #92
