### ISSUE TITLE
DJ for kickoff party

### ISSUE THREAD

**Issue by ana0** [ournetworks/2018#75]
I'm thinking of approaching Julia, who djs around the city and writes for weird canada: https://weirdcanada.com/tag/julia-dickens/  And makes mixtapes: http://lovingecho.tumblr.com/

Any objections?  Other suggestions?  We may need more than 1 dj, depending on how long the shift is

**Comment by dcwalk** [comment]
Amazing!

Not sure if the flow makes sense to start a DJ before 9 (I could see it working well from like 6ish on?

So some possible takes:

Single DJ
 - 1 shift 9pm until 1am (4 hours) -- my sense is this is the max length we'd want to ask for?
  
----
Two DJs
  - 1st shift 6-8pm <break> 9-10pm
  - 2nd shift 10pm - 1:30isham

My only concern is understanding what appropriate compensation would be for either!

I have some (somewhat distant) folks I could ask around about DJing too, but no one immediate in mind

**Comment by ana0** [comment]
Looking at the Bit Bazaar site, we're advertising:

> Friday July 13 • 3 p.m. – 9 p.m.
> The Our Networks Kickoff Party will follow from 10 p.m.-late

I'm good with sticking to that, and having one shift from 9 or 10 until 1:00.

**Comment by ana0** [comment]
Julia is confirmed!  We'll need to add her info to the website
