### ISSUE TITLE
Embed/Present livestream on website

### ISSUE THREAD

**Issue by garrying** [ournetworks/2018#79]
Discussed status after walkthru:
- [x] initial merge
- [x] fix CORS/https issues
- [x] banner with livestream details in https://github.com/ournetworks/ournetworks.ca/pull/67

---

@benhylau Capturing what we talked with livestream embedding on the website:
- Need a decision on having the player on the homepage or separate page
- Define front end requirements:
  - Player JS library (What's recommended?)
  - `.m3u` address to HLS
  - http stream embed
  - ipfs-via-http-gateway stream embed

**Comment by benhylau** [comment]
I would prefer having the player embedded. There is the http stream and the ipfs-via-http-gateway stream. A page to show two players side by side, or have tabs to switch between them?

Related. This ticket will be done in next couple days:
https://github.com/tomeshnet/ipfs-live-streaming/issues/13

**Comment by dcwalk** [comment]
From walkthrough today:
- This was merged
- Origin https then merged

**Comment by dcwalk** [comment]
Done!
