### ISSUE TITLE
Can we support a remote presentation on our stream?

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#88]
Question based on changing availability from presenter... we are thinking:

- Slides shared in advance
- Video call with presenter
- Facilitated live Q&A

Fallback:
- Record presentation 15/mins
- Facilitated live Q&A

**Comment by benhylau** [comment]
AV team is aware of the requirements and we think this is manageable.

Waiting on venue walkthrough to confirm details. How to interface with the venue audio system is undecided until we try things out at the walkthrough.

The options here is communicated to remote presenters.

**Comment by dcwalk** [comment]
It sounds like our answer has been a resounding yes! Discussion / prep happening in #108 #109 etc... and in other repo.

Closing 🎉
