### ISSUE TITLE
create call for submissions

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#9]
Sorry, had to go the academic tooling route, drafting here: https://docs.google.com/document/d/14-N79UdKsayX995NPaNj4a2snVqs3aP2rFS2MfKoHVI/edit

At [2018-02-24 call](https://hackmd.io/s/HkXytz1dG) we identified the remaining TODOs for this:
- [x] test prose for templating (@patcon) and @benhylau did a issue-based flow for submissions
- [x] make decision on submission mechanism (&co) -- github issues new repo
- [x] review CFP text (@dcwalk &co)
- [x] final CFP polish (@dcwalk) -- final markdown-formatted CFP: https://hackmd.io/s/S1wc8p-OG#
- [x] set up submission repo (@dcwalk) - [`2018-submissions`](https://github.com/ournetworks/2018-submissions)
- up on website (handled in #25)

will finish by weekend!

**Comment by dcwalk** [comment]
Some portion of submissions process will be addressed in #31

**Comment by patcon** [comment]
After like a half-hour of testing and digging into code, I'm pretty sure that customizing the content area of the prose.io "new file" page isn't possible :(
Re: https://github.com/prose/prose/pull/437

So I think the best it could be is that we say "copy this text into a new file and fill in the blanks". It's a small step, but I'd understand if that makes prose not worth it.

Alternatively, I also have push access on the prose repo, and it's hosted on github pages. So if we do it respectfully, we _technically_ have the ability to make this work for us

**Comment by benhylau** [comment]
The main issue I have with using prose.io is that it would require me to let prose.io access all my public repositories. There is no granularity to let it only access this one repo. So the minimal requirement now for me to submit a proposal becomes:

1. Have a GitHub account
1. Authorize prose.io to access all of my public repositories

I think it is much simpler to file a _Github Issue_ with an _Github Issue Template_. See example repository I made for this: https://github.com/benhylau/issue-template/issues/new

**Comment by dcwalk** [comment]
@benhylau -- I didn't think prose would be presented as a _requirement_ to submit, more an option for people who are unfamiliar with the github PR flow.

**Comment by dcwalk** [comment]
Thanks people for reviewing CFP, I did another pass yesterday and this morning. There are lingering comments in the middle para I will polish tonight, and then all that is left is WORKFLOW!!!!!

So can we do a basic vote on this issue comment?
🎉 = PR with optional prose submission in `2018` repo
❤️ = Github issue and template in `2018-submissions` standalone repo

attn: @patcon @benhylau @garrying @jkms

**Comment by patcon** [comment]
@benhylau see my comment to the hacks/hackers folks: https://github.com/hackshackers/hackshackers-hugo/pull/86#issuecomment-366399224

the one additional bit of new info since then is that it's been non-https up until now, but that's getting resolved this week apparently: https://github.com/prose/prose/issues/825#issuecomment-368349726

**Comment by patcon** [comment]
GitHub issue edits are totally doable, although a little less collaborative, which is ironic, but not overly so :)

**Comment by dcwalk** [comment]
great thanks for voting! Looks like issue route, I'll set up the process this evening :)

**Comment by dcwalk** [comment]
okay I lied, anyone wanna take a look make sure I'm not missing something: https://github.com/ournetworks/2018-submissions?

Also added some signage (and issue template, sorry! not-sorry!) for this repo to steer people over there hopefully

**Comment by patcon** [comment]
Looks rad! My one thought might be to use ournetworks.ca/cfp and just [use jekyll redirects](https://help.github.com/articles/redirects-on-github-pages/) to the front page while it's there? Feels less link rotty, I suppose :)

**Comment by dcwalk** [comment]
Hey @patcon if I understand correctly I think 👍 from me! Only thought is whether ournetworks.ca/2018 rather than cfp would make sense? (the previous year lives on /2017) let's move convo to a PR in ournetworks.ca tho! 🙏

**Comment by patcon** [comment]
Oh! I forgot it was a one-pager :) Thought there was going to be a CFP page, but was on front-page until even got closer. Nevermind on original intent, but could use years still!
