### ISSUE TITLE
Design Paper Program

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#91]
We need an (ideally 1-page) booklet/info sheet with:

- high-level program
- code of conduct deets
- Wifi details
- sponsors

**Comment by garrying** [comment]
@dcwalk Draft for feedback: 
[ournetworks-program-july9.pdf](https://github.com/ournetworks/2018/files/2176592/ournetworks-program-july9.pdf)

I wonder if there's a way of fitting sponsors (tier 3, in-kind) on here? I think the top bits on the second page could be edited to accommodate. Alternatively, we could remove mention of the sprints after the Sunday program and have them listed there.

**Comment by dcwalk** [comment]
I like it!

- it seems like the cell heights that are larger than the standard on Sat/Sun schedule are all larger in inconsistent ways (e.g. bottom spacing different on "Building something together" and "Our Stable Networks") could that be made more consistent?

RE: space for sponsors:
- We didn't commit to putting any branding on printed materials for Tier 3 below, but agree would be nice
- I think we want to keep the sprints mention in
- Could we aim to have the title splash as more like 2/3 of the front page, give room for a "small" tier of logos for tier 3, in kind, venue?
- We will need to add last sponsor as large: MakerDao

**Comment by garrying** [comment]
@dcwalk Updated version with the edits and including the sponsor logos on the front, which I think works. We're waiting on Quantum Coffee's logo?

[ournetworks-program-july9-v2.pdf](https://github.com/ournetworks/2018/files/2178633/ournetworks-program-july9-v2.pdf)

RE spacing: I evened out some of the rows, and added a bit more whitespace. Does it address what you are spotting? Thinking I might not be seeing the inconsistencies.

**Comment by dcwalk** [comment]
Looking good!

A couple thoughts:

- MakerDao height is throwing me (phew and we should add to website
- We'll need to add in quantum
 [some](https://format-com-cld-res.cloudinary.com/image/private/s--kuYD4X7K--/c_limit,g_center,h_65535,w_2500/a_auto,fl_keep_iptc.progressive.apng/v1/a62342f7c3030cb252c1929e7a3bfe93/Screen_Shot_2018-04-25_at_10_13_44_PM.png), [lifted](http://cdn.shopify.com/s/files/1/1046/2808/t/13/assets/logo.png?8887325095602979637), [logos](https://coffeejobsboard.com/wp-content/uploads/wpjobboard/company/17133/company-logo/01_Quantum_Logo-Black-Outline-Stacked.png)
- aim to print Thursday?

**Comment by garrying** [comment]
Updated with Quantum, and Maker logo height adjust:
[ournetworks-program-july10-v3.pdf](https://github.com/ournetworks/2018/files/2180978/ournetworks-program-july10-v3.pdf)

**Comment by dcwalk** [comment]
@garrying  looks good to me! We should still wait to print until closer too, can you PR the file somewhere? (I think this repo rather than artwork?)
