### ISSUE TITLE
Set up mailing list for next year

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2018#95]
TODOs:
- [x] set up initial list (ournetworks _at_ lists.mayfirst.org ; https://lists.mayfirst.org/mailman/listinfo/ournetworks)
- [x] config as announce only
- [x] add existing list!
- [x] update website copy and signup to point to mailing list (in https://github.com/ournetworks/ournetworks.ca/pull/83)

---

We should decide if/how we want to ask people to get a notification in the future (next year already in my mind?!?)

Discussion at retrospective on how to properly handle a mailing list for those who opted in to updates, seems we have a few options groups:

1. self-host 😨  (e.g., mailman)
2. partial self-host using existing mailserver (@dcwalk seems to think there are options here -- e.g. civicrm?)
3. mutual aid/smaller hosted (e.g., with a local or values-aligned group)
    - mayfirst
    - riseup
    - Toronto connections?
    - Seattle Mesh
4. small- to mega- hosted 
    - tinyletter
    - mailchimp
    - constant contact... etc...

**Comment by dcwalk** [comment]
Discussed at the retrospective and consensed to go ahead with a mailing list.

I've researched mayfirst and think we are okay to use it, however it'll take longer to set up than we thought (also there may be longevity issues there)

**Comment by dcwalk** [comment]
Update: I should be ready as a member to set this up properly tomorrow/Thursday, will aim to test it before email out!

**Comment by dcwalk** [comment]
Okay testing and set up a prelim list here: https://lists.mayfirst.org/mailman/listinfo/ournetworks

**Comment by dcwalk** [comment]
FINAL EMAIL was sent out 🎉 just need to update website to close this out

**Comment by dcwalk** [comment]
Wasn't sure the best way to attempt a smooth website signup for mailman 2.x, could test something like this: https://szabgab.com/how-to-integrate-a-mailman-signup-with-your-web-site.html

**Comment by benhylau** [comment]
Relevant: https://translate.googleusercontent.com/translate_c?depth=1&hl=es&rurl=translate.google.com&sl=ca&sp=nmt4&tl=en&u=https://tec.lleialtat.cat/infraestructura/butlleti&xid=17259,15700023,15700124,15700149,15700186,15700191,15700201&usg=ALkJrhg8A4yNqY7agDVs0s1RISdtOfETHA

**Comment by dcwalk** [comment]
DEAR GOD THIS IS DONE, tho nice link @benhylau on mailtrain. Maybe we think about that down the road 🤷‍♀️
